import type { Metadata } from 'next'
import './globals.css'
import Nav from '@/components/layout/nav'
import Footer from '@/components/layout/footer'
import WordsSlideRight from '@/lib/WordsSlideRight'
import LinesSlideUp from '@/lib/LinesSlideUp'
import CounterAnimation from '@/lib/CounterAnimation'

import LenisScroll from '@/lib/LenisScroll'
import AosInit from '@/lib/aos'

// Metadata must be exported from a Server Component
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AosInit />
      <body>
        <WordsSlideRight />
        <LinesSlideUp />
        <CounterAnimation />
        <LenisScroll>
          <Nav />
          {children}
          <Footer />
        </LenisScroll>
      </body>
    </html>
  )
}
